package com.yht.blog.model;


import java.util.HashSet;
import java.util.Set;

/**
 * Contents generated by hbm2java
 */
public class Contents implements java.io.Serializable {

	private Integer cid;
	private String title;
	private String slug;
	private Integer created;
	private Integer modified;
	private String text;
	private Integer order;
	private Integer authorId;
	private String template;
	private String type;
	private String status;
	private String password;
	private Integer commentsNum;
	private Character allowComment;
	private Character allowPing;
	private Character allowFeed;
	private Set commentses = new HashSet(0);
	private Set metases = new HashSet(0);

	public Contents() {
	}

	public Contents(String title, String slug, Integer created, Integer modified, String text, Integer order,
			Integer authorId, String template, String type, String status, String password, Integer commentsNum,
			Character allowComment, Character allowPing, Character allowFeed, Set commentses, Set metases) {
		this.title = title;
		this.slug = slug;
		this.created = created;
		this.modified = modified;
		this.text = text;
		this.order = order;
		this.authorId = authorId;
		this.template = template;
		this.type = type;
		this.status = status;
		this.password = password;
		this.commentsNum = commentsNum;
		this.allowComment = allowComment;
		this.allowPing = allowPing;
		this.allowFeed = allowFeed;
		this.commentses = commentses;
		this.metases = metases;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	public Integer getCreated() {
		return this.created;
	}

	public void setCreated(Integer created) {
		this.created = created;
	}

	public Integer getModified() {
		return this.modified;
	}

	public void setModified(Integer modified) {
		this.modified = modified;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	public Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getCommentsNum() {
		return this.commentsNum;
	}

	public void setCommentsNum(Integer commentsNum) {
		this.commentsNum = commentsNum;
	}

	public Character getAllowComment() {
		return this.allowComment;
	}

	public void setAllowComment(Character allowComment) {
		this.allowComment = allowComment;
	}

	public Character getAllowPing() {
		return this.allowPing;
	}

	public void setAllowPing(Character allowPing) {
		this.allowPing = allowPing;
	}

	public Character getAllowFeed() {
		return this.allowFeed;
	}

	public void setAllowFeed(Character allowFeed) {
		this.allowFeed = allowFeed;
	}

	public Set getCommentses() {
		return this.commentses;
	}

	public void setCommentses(Set commentses) {
		this.commentses = commentses;
	}

	public Set getMetases() {
		return this.metases;
	}

	public void setMetases(Set metases) {
		this.metases = metases;
	}

}
