package com.yht.blog.model;

import java.util.HashSet;
import java.util.Set;

/**
 * Metas generated by hbm2java
 */
public class Metas implements java.io.Serializable {

	private Integer mid;
	private String name;
	private String slug;
	private String type;
	private String description;
	private Integer count;
	private Integer order;
	private Set contentses = new HashSet(0);

	public Metas() {
	}

	public Metas(String name, String slug, String type, String description, Integer count, Integer order,
			Set contentses) {
		this.name = name;
		this.slug = slug;
		this.type = type;
		this.description = description;
		this.count = count;
		this.order = order;
		this.contentses = contentses;
	}

	public Integer getMid() {
		return this.mid;
	}

	public void setMid(Integer mid) {
		this.mid = mid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	public Set getContentses() {
		return this.contentses;
	}

	public void setContentses(Set contentses) {
		this.contentses = contentses;
	}

}
